import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "../Components/Header/Header";

const geistSans = localFont({
  src: "./fonts/Unbounded-Regular.woff2",
  variable: "--font-unbounded",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/CopperplateCC.woff2",
  variable: "--font-copperplate",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Recipe genie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
